version: "3"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
    - "8080:8080"
  front:
    build: ./frontend
    restart: always
    ports:
    - "8000:80"

  postgres:
    restart: unless-stopped
    image: dockerhub.ir/postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./dummy-data:/dummy-data
    ports:
    - "5432:5432"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"


